[WIP] App installable now
[IMP] Show unit price when qty is not 1

Conflicts:
	pos_pricelist/__openerp__.py

(cherry-pick commit: e9ac0d5d7ac272666e750fbab6c3a39a9af0357b)

[IMP] Preserve manually modified price in most cases

Conflicts:
	pos_pricelist/static/src/js/models.js

(cherry-pick commit: a10bc113c1b602fa80c725a82045c9b1c2eeaa09)

Add contributors

Add contributors

Corrected error: TypeError: Cannot read property 'field' of undefined (and many others before it)
Error occurred: TypeError: Cannot read property 'models' of undefined (in progress)

Recovery db.js

Corrected error: TypeError: Cannot read property 'models' of undefined

Corrected error: TypeError: round_pr is not a function

Corrected error: AttributeError: 'float' object has no attribute 'decimal_places'
Corrected error: KeyError: 'total'

Corrected error: TypeError: _amount_line_tax() got an unexpected keyword argument 'context'

Recovery tooltips (in progress)

Recovery tooltips: corrected compute_price

Check discount values in pricelist cards and remove outdated fields

Corrected calculate discount and remove outdated code

Added percent_price and fixed_price method define discount

Add author in __openerp__.py

Few corrections

Add images and license keys

Corrected license value

Corrected outdated parameters

Correction errors display discounts related to the pricelist customers

Refactoring

[FIX] pos_pricelist: FP taxes with multi-company. Fixes #84

The object account.fiscal.position.tax doesn't have multi-company rules,
which leads to error in environments with multi-company and these records,
because it finally accesses to the parent fiscal position, which on contrary
has access rules, provoking an access error.

This commit added the field company_id to the model, and add the corresponding
access rule.

Conflicts:
	pos_pricelist/__openerp__.py

Added sort rules by applied_on field

Added applied_on field

[FIX] bug when find item

[FIX] bug when find item

[FIX] check product_tmpl_id when collect rules (db.js) and items (models.js)

Add return on method for API call convenience

Force order of product fields loading

[FIX] fix handle where rule.base == 'pricelist'

[IMP]Prevent useless supplierinfo loading

[IMP]Deal with dates in pricelist items

[FIX] initialize() method with ...initialize.apply(this, arguments); must have return

[FIX] Moved ...initialize.apply(this, arguments); to its original place